version: '3.7'

services:
      
  database:
    container_name: testdb
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    volumes:
      - ./data/postdb:/var/lib/postgresql

  
    